### ISSUE TITLE
Not able to access orders after completing quick start

### ISSUE THREAD

**Issue by hetkpatel** [aws-quickstart/quickstart-amazon-selling-partner-api#10]
I've gone through the steps in this quickstart but receive the following error when I run the Lambda Function.

```
Seller participates in the following marketplaces:  {
"errors": [
{
"message": "Access to requested resource is denied.",
"code": "Unauthorized",
"details": ""
}
]
}
```

I deployed the quickstart stack, set up the developer account, and copied the credentials to the `lambda_function.py`.

**Comment by rugved1991** [comment]
Hi @hetkpatel,

Can you confirm if your application has “Seller Insights” role enabled? You can click on ‘edit app’ in the dropdown which is in front of your application in seller central to confirm.

If you haven’t added it to the app, please enable it and reauthorize your application to get a new refresh token and test again.

Best,
Rugved
Solutions Architect, SP API

**Comment by hetkpatel** [comment]
Works! I assumed I only needed "Inventory and Order Tracking" as I was only trying to get order data. Thank you @rugved1991 !
